{% set version = "4.2.0" %}

package:
  name: human-dynamics-estimation-split
  version: {{ version }}

source:
  - url: https://github.com/robotology/human-dynamics-estimation/archive/refs/tags/v{{ version }}.tar.gz
    sha256: c303ebfcb7a74a36c0e2eef0e412a7956eeab25e4816ca2cf7fc28be4f711b0e

build:
  number: 5

outputs:
  - name: libhuman-dynamics-estimation
    script: build_cxx.sh  # [unix]
    script: bld_cxx.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage("libhuman-dynamics-estimation", max_pin='x.x.x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
        - pkg-config
        - ninja
        - multisheller
        # YARP idl tools are used in this recipe
        - libyarp  # [build_platform != target_platform]
      host:
        - ycm-cmake-modules
        - libyarp
        - libicub-main
        - idyntree
        - libosqp
        - osqp-eigen
        - librobometry
        - libmatio-cpp
        - eigen
    test:
      commands:
        - test -f ${PREFIX}/lib/libHumanStateMsg${SHLIB_EXT}  # [unix]
        - if not exist %LIBRARY_LIB%\\HumanStateMsg.lib exit 1  # [win]
        - if not exist %LIBRARY_BIN%\\HumanStateMsg.dll exit 1  # [win]
        - cmake-package-check IWear --targets IWear::IWear
        - cmake-package-check WearableData --targets WearableData::WearableData
        - cmake-package-check WearableActuators --targets WearableActuators::WearableActuators
        - cmake-package-check HumanDynamicsEstimation --targets HumanDynamicsEstimation::HumanStateMsg
      requires:
        - cmake-package-check
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake

  - name: human-dynamics-estimation-python
    script: build_py.sh  # [unix]
    script: bld_py.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
        - pkg-config
        - ninja
        - cross-python_{{ target_platform }}    # [build_platform != target_platform]
        - python                                # [build_platform != target_platform]
      host:
        - {{ pin_subpackage('libhuman-dynamics-estimation', exact=True) }}
        - python
        - libyarp
        - pybind11
        - pybind11-abi
      run:
        - {{ pin_subpackage('libhuman-dynamics-estimation', exact=True) }}
        - python
    test:
      commands:
        - pip check
        - pip list
      imports:
        - wearables
        - hde
      requires:
        - pip

  - name: human-dynamics-estimation
    build:
      run_exports:
        - {{ pin_subpackage("libhuman-dynamics-estimation", max_pin='x.x.x') }}
    requirements:
      run:
        - {{ pin_subpackage("libhuman-dynamics-estimation", exact=True) }}
        - {{ pin_subpackage("human-dynamics-estimation-python", max_pin='x.x.x') }}
    test:
      commands:
        - test -f ${PREFIX}/lib/libHumanStateMsg${SHLIB_EXT}  # [unix]
        - if not exist %LIBRARY_LIB%\\HumanStateMsg.lib exit 1  # [win]
        - if not exist %LIBRARY_BIN%\\HumanStateMsg.dll exit 1  # [win]
        - cmake-package-check IWear --targets IWear::IWear
        - cmake-package-check WearableData --targets WearableData::WearableData
        - cmake-package-check WearableActuators --targets WearableActuators::WearableActuators
        - cmake-package-check WearableActuators --targets WearableActuators::WearableActuators
        - cmake-package-check HumanDynamicsEstimation --targets HumanDynamicsEstimation::HumanStateMsg
        - pip check
        - pip list
      imports:
        - wearables
        - hde
      requires:
        - cmake-package-check
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - pip

about:
  home: https://github.com/robotology/human-dynamics-estimation
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Software repository for estimating human dynamics.'

extra:
  feedstock-name: human-dynamics-estimation
  recipe-maintainers:
    - traversaro
