context:
  version: "5.0.1"

recipe:
  name: human-dynamics-estimation-split
  version: ${{ version }}

source:
  - url: https://github.com/robotology/human-dynamics-estimation/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 01d38db27ed0345a6867b0921efa2b2120c52740e27a36c440150fe5de31c02b

build:
  number: 0

outputs:
  - package:
      name: libhuman-dynamics-estimation
    build:
      script:
        - if: unix
          then: build_cxx.sh
        - if: win
          then: bld_cxx.bat
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - pkg-config
        - ninja
        - multisheller
        - if: build_platform != target_platform
          then:
            - libyarp
      host:
        - ycm-cmake-modules
        - libyarp
        - libicub-main
        - libtrintrin
        - idyntree
        - libosqp
        - osqp-eigen
        - librobometry
        - libmatio-cpp
        - eigen
        - eigen-abi-devel
      run_exports:
        - ${{ pin_subpackage('libhuman-dynamics-estimation', upper_bound='x.x.x') }}
    tests:
      - script:
          - cmake-package-check IWear --targets IWear::IWear
        requirements:
          run:
            - cmake-package-check
            - ${{ compiler('c') }}
            - ${{ compiler('cxx') }}
            - cmake

  - package:
      name: human-dynamics-estimation
    requirements:
      run_exports:
        - ${{ pin_subpackage('libhuman-dynamics-estimation', upper_bound='x.x.x') }}
      run:
        - ${{ pin_subpackage('libhuman-dynamics-estimation', exact=True) }}
    tests:
      - script:
          - cmake-package-check IWear --targets IWear::IWear
        requirements:
          run:
            - cmake-package-check
            - ${{ compiler('c') }}
            - ${{ compiler('cxx') }}
            - cmake

about:
  homepage: https://github.com/robotology/human-dynamics-estimation
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Software repository for estimating human dynamics.

extra:
  feedstock-name: human-dynamics-estimation
  recipe-maintainers:
    - traversaro
